import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { fetchAPI } from "@/lib/strapi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getNavbarData() {
  try {
    const path = `/api/home?populate[Navbar][populate][Navlogo]=true&populate[Navbar][populate][Navitems]=*&populate[Navbar][populate][Navbutton]=*&populate[Navbar][populate][Navdropdown][populate][Navitems]=*`;
    const res = await fetchAPI(path);
    return res?.data?.Navbar || null;
  } catch (error) {
    console.error("Error fetching navbar data:", error);
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbarData = await getNavbarData();

  // Assuming the user wants to add this mock data to the navbarData object
  // or use it as a fallback/override.
  // The provided "Code Edit" was syntactically incorrect for direct placement in JSX.
  // This interpretation assumes the user wants to augment the navbarData object
  // with these specific button structures.
  const augmentedNavbarData = {
    ...navbarData,
    Navbutton: {
      Buttonname: 'Get Started',
      Buttonurl: '/register',
      type: 'primary',
      id: 2
    },
    Loginbutton: {
      Buttonname: 'Login',
      Buttonurl: '/login',
      type: 'secondary', // or 'textlink'
      id: 3
    }
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar data={augmentedNavbarData} />
        {children}
      </body>
    </html>
  );
}
